//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealHunter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public string pgid { get; set; }
        public string puid { get; set; }
        public int plow { get; set; }
        public int phigh { get; set; }
        public string pdes { get; set; }
        public string pstate { get; set; }
    
        public virtual goods goods { get; set; }
        public virtual user user { get; set; }
    }
}
