//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealHunter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.goods = new HashSet<goods>();
            this.purchase = new HashSet<purchase>();
        }
    
        public string uid { get; set; }
        public string upwd { get; set; }
        public string upincode { get; set; }
        public string uname { get; set; }
        public string ugender { get; set; }
        public int uage { get; set; }
        public string ucareer { get; set; }
        public string umail { get; set; }
        public string utelephone { get; set; }
        public string uceilphone { get; set; }
        public string uprovince { get; set; }
        public string ucity { get; set; }
        public string udistrict { get; set; }
        public string ustreet { get; set; }
        public string uzipcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<goods> goods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase> purchase { get; set; }
    }
}
